// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DemoBlazor.Models.Entities;

public partial class Clan
{
    public int Id { get; set; }

    public string ClanName { get; set; }

    public virtual ICollection<Samurai> Samurais { get; set; } = new List<Samurai>();
}